export const STANDARD_FORMAT = 'YYYY-MM-DDTHH:mm:ss' // ISO 8601 standard using for query params
export const STANDARD_UK_FORMAT = 'DD/MM/YYTHH:mm:ss'
export const STANDARD_UK_DATE_FORMAT = 'DD/MM/YYYY'
export const DATE_FORMAT = 'YYYY/MM/DD'
export const TIME_FORMATE = 'HH:mm:ss'
export const ORDINAL_DAY_DATE_TIME = 'Do MMMM yyyy'
export const DAY = 'dddd'
export const DEFAULT_TIME_FORMAT = 'H:mm'
export const DEFAULT_DATE_TIME_FORMAT = `${DATE_FORMAT}  ${DEFAULT_TIME_FORMAT}`
